name: "Scan and test"

# Controls when the workflow will run
on:
  push:
    branches: ['main']
    tags:
      - 'v*.*.*'
  pull_request:
    branches: ['main']
  schedule:
    - cron: '18 6 */3 * *'
      # Run builds at 06:18 on every 3rd day-of-month.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # snyk:
  #   name: "Snyk: scanner"
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     security-events: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build a Docker image
  #       run: docker build -t moj/kubernetes-pod-broadcaster .

  #     - name: Run Snyk | Check Docker image for vulnerabilities
  #       uses: snyk/actions/docker@master
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #       with:
  #         image: moj/kubernetes-pod-broadcaster
  #         args: --file=Dockerfile --severity-threshold=medium

  test:
    if: github.event_name == 'pull_request'
    name: "Deno: test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Cache Deno modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}-v2
          restore-keys: |
            ${{ runner.os }}-deno-v2
      - name: Run tests
        run: deno task test
