name: "Test"

# Controls when the workflow will run
on:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    if: github.event_name == 'pull_request'
    name: "Deno: test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build container image
        run: docker image build  -t kubernetes-pod-broadcaster:test .

      - name: Run tests
        run: docker run --rm kubernetes-pod-broadcaster:test sh -c "deno run test"
